{
 "title": "Sensors",
 "description": "Dashboard for detailed view of metrics from https://github.com/ncabatoff/sensor-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sensor_lm_temperature_celsius", "legendFormat": "{{temptype}}" }
   ]
  },
  {
   "title": "Temperatures deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(sensor_lm_temperature_celsius[$interval]) > 0.00001 or deriv(sensor_lm_temperature_celsius[$interval]) < -0.00001",
     "legendFormat": "{{temptype}}"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sensor_lm_fan_speed_rpm", "legendFormat": "{{fantype}}" }
   ]
  },
  {
   "title": "Fan speed deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(sensor_lm_fan_speed_rpm[$interval])",
     "legendFormat": "{{fantype}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sensor_lm_voltage_volts", "legendFormat": "{{intype}}" }
   ]
  },
  {
   "title": "Voltage deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(sensor_lm_voltage_volts[$interval])",
     "legendFormat": "{{intype}}"
    }
   ]
  },
  {
   "title": "sensor exporter resident mem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"sensor\"}"
    }
   ]
  },
  {
   "title": "sensor exporter resident mem deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "deriv(process_resident_memory_bytes{job=\"sensor\"}[$interval])"
    }
   ]
  },
  {
   "title": "sensor exporter up",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"sensor\"}"
    }
   ]
  },
  {
   "title": "sensor scrape duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"sensor\"}"
    }
   ]
  },
  {
   "title": "HDD temps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sensor_hddsmart_temperature_celsius",
     "legendFormat": "{{device}} {{id}}"
    }
   ]
  },
  {
   "title": "HDD temps deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(sensor_hddsmart_temperature_celsius[$interval])",
     "legendFormat": "{{device}} {{id}}"
    }
   ]
  }
 ]
}